### ISSUE TITLE
Script to update test ids doesn't work

### ISSUE THREAD

**Issue by ken-wesley** [testomatio/check-tests#112] opened 2023-05-25 06:14 UTC
The script that we use to update the test ids does not add new test ids for added test scenarios

Script: TESTOMATIO=b0f2514004q7 npx check-tests@latest CodeceptJS "**/*{.,_}{test,spec}.ts" --typescript --update-ids

Example [file](https://testomatio.slack.com/files/U04RDCMNTPD/F0592R7EA6A/untitled.js)

More info on this [slack thread](https://testomatio.slack.com/archives/C03QZ7C97FS/p1684913985333109).

**Comment by DavertMik** [comment] 2023-05-30 18:03
@ken-wesley the example file you included contains only test that has ID
I am not sure I understand how to solve this issue, looks like I don't have enough information to 
But let's continue the discussion in Slack

**Comment by mykhailiukVitalii** [comment] 2023-06-14 12:32
It looks like this command should work as expected on the latest version check-test. @DavertMik 
Could u double-check, pls? @ken-wesley

**Comment by poliarush** [comment] 2023-06-30 13:21
@ken-wesley please re-check it and let us know

**Comment by poliarush** [comment] 2023-07-26 08:58
@ken-wesley we close this ticket, please re-open if it's reproduced on latest version

**Closed by poliarush** 2023-07-26 08:58 UTC
Labels: bug, priority high, codeceptjs
